// Decompiled with JetBrains decompiler
// Type: Terraria.Initializers.AchievementInitializer
// Assembly: Terraria, Version=1.3.4.4, Culture=neutral, PublicKeyToken=null
// MVID: DEE50102-BCC2-472F-987B-153E892583F1
// Assembly location: C:\Users\Zhi Cai\Documents\terraria source\Terraria1.3.4.4\Terraria\Terraria-cleaned.exe

using Terraria.Achievements;
using Terraria.GameContent.Achievements;
using Terraria.GameContent.UI.Chat;
using Terraria.Localization;

namespace Terraria.Initializers
{
  public class AchievementInitializer
  {
    public static void Load()
    {
      if (Main.netMode == 2)
        return;
      Achievement achievement1 = new Achievement("TIMBER");
      achievement1.AddCondition(ItemPickupCondition.Create((short) 9, (short) 619, (short) 2504, (short) 620, (short) 2503, (short) 2260, (short) 621, (short) 911, (short) 1729));
      Main.Achievements.Register(achievement1);
      Achievement achievement2 = new Achievement("NO_HOBO");
      achievement2.AddCondition((AchievementCondition) ProgressionEventCondition.Create(8));
      Main.Achievements.Register(achievement2);
      Achievement achievement3 = new Achievement("OBTAIN_HAMMER");
      achievement3.AddCondition(ItemPickupCondition.Create((short) 2775, (short) 2746, (short) 3505, (short) 654, (short) 3517, (short) 7, (short) 3493, (short) 2780, (short) 1513, (short) 2516, (short) 660, (short) 3481, (short) 657, (short) 922, (short) 3511, (short) 2785, (short) 3499, (short) 3487, (short) 196, (short) 367, (short) 104, (short) 797, (short) 2320, (short) 787, (short) 1234, (short) 1262, (short) 3465, (short) 204, (short) 217, (short) 1507, (short) 3524, (short) 3522, (short) 3525, (short) 3523, (short) 1305));
      Main.Achievements.Register(achievement3);
      Achievement achievement4 = new Achievement("OOO_SHINY");
      achievement4.AddCondition(TileDestroyedCondition.Create((ushort) 7, (ushort) 6, (ushort) 9, (ushort) 8, (ushort) 166, (ushort) 167, (ushort) 168, (ushort) 169, (ushort) 22, (ushort) 204, (ushort) 58, (ushort) 107, (ushort) 108, (ushort) 111, (ushort) 221, (ushort) 222, (ushort) 223, (ushort) 211));
      Main.Achievements.Register(achievement4);
      Achievement achievement5 = new Achievement("HEART_BREAKER");
      achievement5.AddCondition(TileDestroyedCondition.Create((ushort) 12));
      Main.Achievements.Register(achievement5);
      Achievement achievement6 = new Achievement("HEAVY_METAL");
      achievement6.AddCondition(ItemPickupCondition.Create((short) 35, (short) 716));
      Main.Achievements.Register(achievement6);
      Achievement achievement7 = new Achievement("I_AM_LOOT");
      achievement7.AddCondition(CustomFlagCondition.Create("Peek"));
      Main.Achievements.Register(achievement7);
      Achievement achievement8 = new Achievement("STAR_POWER");
      achievement8.AddCondition(CustomFlagCondition.Create("Use"));
      Main.Achievements.Register(achievement8);
      Achievement achievement9 = new Achievement("HOLD_ON_TIGHT");
      achievement9.AddCondition(CustomFlagCondition.Create("Equip"));
      Main.Achievements.Register(achievement9);
      Achievement achievement10 = new Achievement("EYE_ON_YOU");
      achievement10.AddCondition(NPCKilledCondition.Create((short) 4));
      Main.Achievements.Register(achievement10);
      Achievement achievement11 = new Achievement("SMASHING_POPPET");
      achievement11.AddCondition((AchievementCondition) ProgressionEventCondition.Create(7));
      Main.Achievements.Register(achievement11);
      Achievement achievement12 = new Achievement("WORM_FODDER");
      achievement12.AddCondition(NPCKilledCondition.Create((short) 13, (short) 14, (short) 15));
      Main.Achievements.Register(achievement12);
      Achievement achievement13 = new Achievement("MASTERMIND");
      achievement13.AddCondition(NPCKilledCondition.Create((short) 266));
      Main.Achievements.Register(achievement13);
      Achievement achievement14 = new Achievement("WHERES_MY_HONEY");
      achievement14.AddCondition(CustomFlagCondition.Create("Reach"));
      Main.Achievements.Register(achievement14);
      Achievement achievement15 = new Achievement("STING_OPERATION");
      achievement15.AddCondition(NPCKilledCondition.Create((short) 222));
      Main.Achievements.Register(achievement15);
      Achievement achievement16 = new Achievement("BONED");
      achievement16.AddCondition(NPCKilledCondition.Create((short) 35));
      Main.Achievements.Register(achievement16);
      Achievement achievement17 = new Achievement("DUNGEON_HEIST");
      achievement17.AddCondition(ItemPickupCondition.Create((short) 327));
      achievement17.AddCondition((AchievementCondition) ProgressionEventCondition.Create(19));
      Main.Achievements.Register(achievement17);
      Achievement achievement18 = new Achievement("ITS_GETTING_HOT_IN_HERE");
      achievement18.AddCondition(CustomFlagCondition.Create("Reach"));
      Main.Achievements.Register(achievement18);
      Achievement achievement19 = new Achievement("MINER_FOR_FIRE");
      achievement19.AddCondition(ItemCraftCondition.Create((short) 122));
      Main.Achievements.Register(achievement19);
      Achievement achievement20 = new Achievement("STILL_HUNGRY");
      achievement20.AddCondition(NPCKilledCondition.Create((short) 113, (short) 114));
      Main.Achievements.Register(achievement20);
      Achievement achievement21 = new Achievement("ITS_HARD");
      achievement21.AddCondition((AchievementCondition) ProgressionEventCondition.Create(9));
      Main.Achievements.Register(achievement21);
      Achievement achievement22 = new Achievement("BEGONE_EVIL");
      achievement22.AddCondition((AchievementCondition) ProgressionEventCondition.Create(6));
      Main.Achievements.Register(achievement22);
      Achievement achievement23 = new Achievement("EXTRA_SHINY");
      achievement23.AddCondition(TileDestroyedCondition.Create((ushort) 107, (ushort) 108, (ushort) 111, (ushort) 221, (ushort) 222, (ushort) 223));
      Main.Achievements.Register(achievement23);
      Achievement achievement24 = new Achievement("HEAD_IN_THE_CLOUDS");
      achievement24.AddCondition(CustomFlagCondition.Create("Equip"));
      Main.Achievements.Register(achievement24);
      Achievement achievement25 = new Achievement("LIKE_A_BOSS");
      achievement25.AddCondition(ItemPickupCondition.Create((short) 1133, (short) 1331, (short) 1307, (short) 267, (short) 1293, (short) 557, (short) 544, (short) 556, (short) 560, (short) 43, (short) 70));
      Main.Achievements.Register(achievement25);
      Achievement achievement26 = new Achievement("BUCKETS_OF_BOLTS");
      achievement26.AddCondition(NPCKilledCondition.Create((short) 125, (short) 126));
      achievement26.AddConditions(NPCKilledCondition.CreateMany((short) sbyte.MaxValue, (short) 134));
      achievement26.UseConditionsCompletedTracker();
      Main.Achievements.Register(achievement26);
      Achievement achievement27 = new Achievement("DRAX_ATTAX");
      achievement27.AddCondition(ItemCraftCondition.Create((short) 579, (short) 990));
      Main.Achievements.Register(achievement27);
      Achievement achievement28 = new Achievement("PHOTOSYNTHESIS");
      achievement28.AddCondition(TileDestroyedCondition.Create((ushort) 211));
      Main.Achievements.Register(achievement28);
      Achievement achievement29 = new Achievement("GET_A_LIFE");
      achievement29.AddCondition(CustomFlagCondition.Create("Use"));
      Main.Achievements.Register(achievement29);
      Achievement achievement30 = new Achievement("THE_GREAT_SOUTHERN_PLANTKILL");
      achievement30.AddCondition(NPCKilledCondition.Create((short) 262));
      Main.Achievements.Register(achievement30);
      Achievement achievement31 = new Achievement("TEMPLE_RAIDER");
      achievement31.AddCondition(TileDestroyedCondition.Create((ushort) 226));
      Main.Achievements.Register(achievement31);
      Achievement achievement32 = new Achievement("LIHZAHRDIAN_IDOL");
      achievement32.AddCondition(NPCKilledCondition.Create((short) 245));
      Main.Achievements.Register(achievement32);
      Achievement achievement33 = new Achievement("ROBBING_THE_GRAVE");
      achievement33.AddCondition(ItemPickupCondition.Create((short) 1513, (short) 938, (short) 963, (short) 977, (short) 1300, (short) 1254, (short) 1514, (short) 679, (short) 759, (short) 1446, (short) 1445, (short) 1444, (short) 1183, (short) 1266, (short) 671));
      Main.Achievements.Register(achievement33);
      Achievement achievement34 = new Achievement("BIG_BOOTY");
      achievement34.AddCondition((AchievementCondition) ProgressionEventCondition.Create(20));
      Main.Achievements.Register(achievement34);
      Achievement achievement35 = new Achievement("FISH_OUT_OF_WATER");
      achievement35.AddCondition(NPCKilledCondition.Create((short) 370));
      Main.Achievements.Register(achievement35);
      Achievement achievement36 = new Achievement("OBSESSIVE_DEVOTION");
      achievement36.AddCondition(NPCKilledCondition.Create((short) 439));
      Main.Achievements.Register(achievement36);
      Achievement achievement37 = new Achievement("STAR_DESTROYER");
      achievement37.AddConditions(NPCKilledCondition.CreateMany((short) 517, (short) 422, (short) 507, (short) 493));
      Main.Achievements.Register(achievement37);
      Achievement achievement38 = new Achievement("CHAMPION_OF_TERRARIA");
      achievement38.AddCondition(NPCKilledCondition.Create((short) 398));
      Main.Achievements.Register(achievement38);
      Achievement achievement39 = new Achievement("BLOODBATH");
      achievement39.AddCondition((AchievementCondition) ProgressionEventCondition.Create(5));
      Main.Achievements.Register(achievement39);
      Achievement achievement40 = new Achievement("SLIPPERY_SHINOBI");
      achievement40.AddCondition(NPCKilledCondition.Create((short) 50));
      Main.Achievements.Register(achievement40);
      Achievement achievement41 = new Achievement("GOBLIN_PUNTER");
      achievement41.AddCondition((AchievementCondition) ProgressionEventCondition.Create(10));
      Main.Achievements.Register(achievement41);
      Achievement achievement42 = new Achievement("WALK_THE_PLANK");
      achievement42.AddCondition((AchievementCondition) ProgressionEventCondition.Create(11));
      Main.Achievements.Register(achievement42);
      Achievement achievement43 = new Achievement("KILL_THE_SUN");
      achievement43.AddCondition((AchievementCondition) ProgressionEventCondition.Create(3));
      Main.Achievements.Register(achievement43);
      Achievement achievement44 = new Achievement("DO_YOU_WANT_TO_SLAY_A_SNOWMAN");
      achievement44.AddCondition((AchievementCondition) ProgressionEventCondition.Create(12));
      Main.Achievements.Register(achievement44);
      Achievement achievement45 = new Achievement("TIN_FOIL_HATTER");
      achievement45.AddCondition((AchievementCondition) ProgressionEventCondition.Create(13));
      Main.Achievements.Register(achievement45);
      Achievement achievement46 = new Achievement("BALEFUL_HARVEST");
      achievement46.AddCondition((AchievementCondition) ProgressionEventCondition.Create(15));
      Main.Achievements.Register(achievement46);
      Achievement achievement47 = new Achievement("ICE_SCREAM");
      achievement47.AddCondition((AchievementCondition) ProgressionEventCondition.Create(14));
      Main.Achievements.Register(achievement47);
      Achievement achievement48 = new Achievement("STICKY_SITUATION");
      achievement48.AddCondition((AchievementCondition) ProgressionEventCondition.Create(16));
      Main.Achievements.Register(achievement48);
      Achievement achievement49 = new Achievement("REAL_ESTATE_AGENT");
      achievement49.AddCondition((AchievementCondition) ProgressionEventCondition.Create(17));
      Main.Achievements.Register(achievement49);
      Achievement achievement50 = new Achievement("NOT_THE_BEES");
      achievement50.AddCondition(CustomFlagCondition.Create("Use"));
      Main.Achievements.Register(achievement50);
      Achievement achievement51 = new Achievement("JEEPERS_CREEPERS");
      achievement51.AddCondition(CustomFlagCondition.Create("Reach"));
      Main.Achievements.Register(achievement51);
      Achievement achievement52 = new Achievement("FUNKYTOWN");
      achievement52.AddCondition(CustomFlagCondition.Create("Reach"));
      Main.Achievements.Register(achievement52);
      Achievement achievement53 = new Achievement("INTO_ORBIT");
      achievement53.AddCondition(CustomFlagCondition.Create("Reach"));
      Main.Achievements.Register(achievement53);
      Achievement achievement54 = new Achievement("ROCK_BOTTOM");
      achievement54.AddCondition(CustomFlagCondition.Create("Reach"));
      Main.Achievements.Register(achievement54);
      Achievement achievement55 = new Achievement("MECHA_MAYHEM");
      achievement55.AddCondition((AchievementCondition) ProgressionEventCondition.Create(21));
      Main.Achievements.Register(achievement55);
      Achievement achievement56 = new Achievement("GELATIN_WORLD_TOUR");
      achievement56.AddConditions(NPCKilledCondition.CreateMany((short) -5, (short) -6, (short) 1, (short) 81, (short) 71, (short) -3, (short) 147, (short) 138, (short) -10, (short) 50, (short) 59, (short) 16, (short) -7, (short) 244, (short) -8, (short) -1, (short) -2, (short) 184, (short) 204, (short) 225, (short) -9, (short) 141, (short) 183, (short) -4));
      achievement56.UseConditionsCompletedTracker();
      Main.Achievements.Register(achievement56);
      Achievement achievement57 = new Achievement("FASHION_STATEMENT");
      achievement57.AddCondition(CustomFlagCondition.Create("Equip"));
      Main.Achievements.Register(achievement57);
      Achievement achievement58 = new Achievement("VEHICULAR_MANSLAUGHTER");
      achievement58.AddCondition(CustomFlagCondition.Create("Hit"));
      Main.Achievements.Register(achievement58);
      Achievement achievement59 = new Achievement("BULLDOZER");
      achievement59.AddCondition(CustomIntCondition.Create("Pick", 10000));
      achievement59.UseTrackerFromCondition("Pick");
      Main.Achievements.Register(achievement59);
      Achievement achievement60 = new Achievement("THERE_ARE_SOME_WHO_CALL_HIM");
      achievement60.AddCondition(NPCKilledCondition.Create((short) 45));
      Main.Achievements.Register(achievement60);
      Achievement achievement61 = new Achievement("DECEIVER_OF_FOOLS");
      achievement61.AddCondition(NPCKilledCondition.Create((short) 196));
      Main.Achievements.Register(achievement61);
      Achievement achievement62 = new Achievement("SWORD_OF_THE_HERO");
      achievement62.AddCondition(ItemPickupCondition.Create((short) 757));
      Main.Achievements.Register(achievement62);
      Achievement achievement63 = new Achievement("LUCKY_BREAK");
      achievement63.AddCondition(CustomFlagCondition.Create("Hit"));
      Main.Achievements.Register(achievement63);
      Achievement achievement64 = new Achievement("THROWING_LINES");
      achievement64.AddCondition(CustomFlagCondition.Create("Use"));
      Main.Achievements.Register(achievement64);
      Achievement achievement65 = new Achievement("DYE_HARD");
      achievement65.AddCondition(CustomFlagCondition.Create("Equip"));
      Main.Achievements.Register(achievement65);
      Achievement achievement66 = new Achievement("SICK_THROW");
      achievement66.AddCondition(ItemPickupCondition.Create((short) 3389));
      Main.Achievements.Register(achievement66);
      Achievement achievement67 = new Achievement("FREQUENT_FLYER");
      achievement67.AddCondition(CustomFloatCondition.Create("Pay", 10000f));
      achievement67.UseTrackerFromCondition("Pay");
      Main.Achievements.Register(achievement67);
      Achievement achievement68 = new Achievement("THE_CAVALRY");
      achievement68.AddCondition(CustomFlagCondition.Create("Equip"));
      Main.Achievements.Register(achievement68);
      Achievement achievement69 = new Achievement("COMPLETELY_AWESOME");
      achievement69.AddCondition(ItemPickupCondition.Create((short) 98));
      Main.Achievements.Register(achievement69);
      Achievement achievement70 = new Achievement("TIL_DEATH");
      achievement70.AddCondition(NPCKilledCondition.Create((short) 53));
      Main.Achievements.Register(achievement70);
      Achievement achievement71 = new Achievement("ARCHAEOLOGIST");
      achievement71.AddCondition(NPCKilledCondition.Create((short) 52));
      Main.Achievements.Register(achievement71);
      Achievement achievement72 = new Achievement("PRETTY_IN_PINK");
      achievement72.AddCondition(NPCKilledCondition.Create((short) -4));
      Main.Achievements.Register(achievement72);
      Achievement achievement73 = new Achievement("RAINBOWS_AND_UNICORNS");
      achievement73.AddCondition(CustomFlagCondition.Create("Use"));
      Main.Achievements.Register(achievement73);
      Achievement achievement74 = new Achievement("YOU_AND_WHAT_ARMY");
      achievement74.AddCondition(CustomFlagCondition.Create("Spawn"));
      Main.Achievements.Register(achievement74);
      Achievement achievement75 = new Achievement("PRISMANCER");
      achievement75.AddCondition(ItemPickupCondition.Create((short) 495));
      Main.Achievements.Register(achievement75);
      Achievement achievement76 = new Achievement("IT_CAN_TALK");
      achievement76.AddCondition((AchievementCondition) ProgressionEventCondition.Create(18));
      Main.Achievements.Register(achievement76);
      Achievement achievement77 = new Achievement("WATCH_YOUR_STEP");
      achievement77.AddCondition(CustomFlagCondition.Create("Hit"));
      Main.Achievements.Register(achievement77);
      Achievement achievement78 = new Achievement("MARATHON_MEDALIST");
      achievement78.AddCondition(CustomFloatCondition.Create("Move", 1106688f));
      achievement78.UseTrackerFromCondition("Move");
      Main.Achievements.Register(achievement78);
      Achievement achievement79 = new Achievement("GLORIOUS_GOLDEN_POLE");
      achievement79.AddCondition(ItemPickupCondition.Create((short) 2294));
      Main.Achievements.Register(achievement79);
      Achievement achievement80 = new Achievement("SERVANT_IN_TRAINING");
      achievement80.AddCondition(CustomFlagCondition.Create("Finish"));
      Main.Achievements.Register(achievement80);
      Achievement achievement81 = new Achievement("GOOD_LITTLE_SLAVE");
      achievement81.AddCondition(CustomIntCondition.Create("Finish", 10));
      achievement81.UseTrackerFromCondition("Finish");
      Main.Achievements.Register(achievement81);
      Achievement achievement82 = new Achievement("TROUT_MONKEY");
      achievement82.AddCondition(CustomIntCondition.Create("Finish", 25));
      achievement82.UseTrackerFromCondition("Finish");
      Main.Achievements.Register(achievement82);
      Achievement achievement83 = new Achievement("FAST_AND_FISHIOUS");
      achievement83.AddCondition(CustomIntCondition.Create("Finish", 50));
      achievement83.UseTrackerFromCondition("Finish");
      Main.Achievements.Register(achievement83);
      Achievement achievement84 = new Achievement("SUPREME_HELPER_MINION");
      achievement84.AddCondition(CustomIntCondition.Create("Finish", 200));
      achievement84.UseTrackerFromCondition("Finish");
      Main.Achievements.Register(achievement84);
      Achievement achievement85 = new Achievement("TOPPED_OFF");
      achievement85.AddCondition(CustomFlagCondition.Create("Use"));
      Main.Achievements.Register(achievement85);
      Achievement achievement86 = new Achievement("SLAYER_OF_WORLDS");
      achievement86.AddCondition(NPCKilledCondition.Create((short) 13, (short) 14, (short) 15));
      achievement86.AddCondition(NPCKilledCondition.Create((short) 113, (short) 114));
      achievement86.AddCondition(NPCKilledCondition.Create((short) 125, (short) 126));
      achievement86.AddConditions(NPCKilledCondition.CreateMany((short) 4, (short) 35, (short) 50, (short) 222, (short) 113, (short) 134, (short) sbyte.MaxValue, (short) 262, (short) 245, (short) 439, (short) 398, (short) 370));
      achievement86.UseConditionsCompletedTracker();
      Main.Achievements.Register(achievement86);
      Achievement achievement87 = new Achievement("YOU_CAN_DO_IT");
      achievement87.AddCondition((AchievementCondition) ProgressionEventCondition.Create(1));
      Main.Achievements.Register(achievement87);
      Achievement achievement88 = new Achievement("MATCHING_ATTIRE");
      achievement88.AddCondition(CustomFlagCondition.Create("Equip"));
      Main.Achievements.Register(achievement88);
      Main.Achievements.RegisterIconIndex("TIMBER", 0);
      Main.Achievements.RegisterIconIndex("NO_HOBO", 1);
      Main.Achievements.RegisterIconIndex("OBTAIN_HAMMER", 2);
      Main.Achievements.RegisterIconIndex("HEART_BREAKER", 3);
      Main.Achievements.RegisterIconIndex("OOO_SHINY", 4);
      Main.Achievements.RegisterIconIndex("HEAVY_METAL", 5);
      Main.Achievements.RegisterIconIndex("I_AM_LOOT", 6);
      Main.Achievements.RegisterIconIndex("STAR_POWER", 7);
      Main.Achievements.RegisterIconIndex("HOLD_ON_TIGHT", 8);
      Main.Achievements.RegisterIconIndex("EYE_ON_YOU", 9);
      Main.Achievements.RegisterIconIndex("SMASHING_POPPET", 10);
      Main.Achievements.RegisterIconIndex("WORM_FODDER", 11);
      Main.Achievements.RegisterIconIndex("MASTERMIND", 12);
      Main.Achievements.RegisterIconIndex("WHERES_MY_HONEY", 13);
      Main.Achievements.RegisterIconIndex("STING_OPERATION", 14);
      Main.Achievements.RegisterIconIndex("BONED", 15);
      Main.Achievements.RegisterIconIndex("DUNGEON_HEIST", 16);
      Main.Achievements.RegisterIconIndex("ITS_GETTING_HOT_IN_HERE", 17);
      Main.Achievements.RegisterIconIndex("MINER_FOR_FIRE", 18);
      Main.Achievements.RegisterIconIndex("STILL_HUNGRY", 19);
      Main.Achievements.RegisterIconIndex("ITS_HARD", 20);
      Main.Achievements.RegisterIconIndex("BEGONE_EVIL", 21);
      Main.Achievements.RegisterIconIndex("EXTRA_SHINY", 22);
      Main.Achievements.RegisterIconIndex("HEAD_IN_THE_CLOUDS", 23);
      Main.Achievements.RegisterIconIndex("LIKE_A_BOSS", 24);
      Main.Achievements.RegisterIconIndex("BUCKETS_OF_BOLTS", 25);
      Main.Achievements.RegisterIconIndex("DRAX_ATTAX", 26);
      Main.Achievements.RegisterIconIndex("PHOTOSYNTHESIS", 27);
      Main.Achievements.RegisterIconIndex("GET_A_LIFE", 28);
      Main.Achievements.RegisterIconIndex("THE_GREAT_SOUTHERN_PLANTKILL", 29);
      Main.Achievements.RegisterIconIndex("TEMPLE_RAIDER", 30);
      Main.Achievements.RegisterIconIndex("LIHZAHRDIAN_IDOL", 31);
      Main.Achievements.RegisterIconIndex("ROBBING_THE_GRAVE", 32);
      Main.Achievements.RegisterIconIndex("BIG_BOOTY", 33);
      Main.Achievements.RegisterIconIndex("FISH_OUT_OF_WATER", 34);
      Main.Achievements.RegisterIconIndex("OBSESSIVE_DEVOTION", 35);
      Main.Achievements.RegisterIconIndex("STAR_DESTROYER", 36);
      Main.Achievements.RegisterIconIndex("CHAMPION_OF_TERRARIA", 37);
      Main.Achievements.RegisterIconIndex("BLOODBATH", 38);
      Main.Achievements.RegisterIconIndex("GOBLIN_PUNTER", 39);
      Main.Achievements.RegisterIconIndex("KILL_THE_SUN", 40);
      Main.Achievements.RegisterIconIndex("WALK_THE_PLANK", 41);
      Main.Achievements.RegisterIconIndex("DO_YOU_WANT_TO_SLAY_A_SNOWMAN", 42);
      Main.Achievements.RegisterIconIndex("TIN_FOIL_HATTER", 43);
      Main.Achievements.RegisterIconIndex("BALEFUL_HARVEST", 44);
      Main.Achievements.RegisterIconIndex("ICE_SCREAM", 45);
      Main.Achievements.RegisterIconIndex("SLIPPERY_SHINOBI", 46);
      Main.Achievements.RegisterIconIndex("STICKY_SITUATION", 47);
      Main.Achievements.RegisterIconIndex("REAL_ESTATE_AGENT", 48);
      Main.Achievements.RegisterIconIndex("NOT_THE_BEES", 49);
      Main.Achievements.RegisterIconIndex("JEEPERS_CREEPERS", 50);
      Main.Achievements.RegisterIconIndex("FUNKYTOWN", 51);
      Main.Achievements.RegisterIconIndex("INTO_ORBIT", 52);
      Main.Achievements.RegisterIconIndex("ROCK_BOTTOM", 53);
      Main.Achievements.RegisterIconIndex("MECHA_MAYHEM", 54);
      Main.Achievements.RegisterIconIndex("GELATIN_WORLD_TOUR", 55);
      Main.Achievements.RegisterIconIndex("FASHION_STATEMENT", 56);
      Main.Achievements.RegisterIconIndex("VEHICULAR_MANSLAUGHTER", 57);
      Main.Achievements.RegisterIconIndex("BULLDOZER", 58);
      Main.Achievements.RegisterIconIndex("THERE_ARE_SOME_WHO_CALL_HIM", 59);
      Main.Achievements.RegisterIconIndex("DECEIVER_OF_FOOLS", 60);
      Main.Achievements.RegisterIconIndex("SWORD_OF_THE_HERO", 61);
      Main.Achievements.RegisterIconIndex("LUCKY_BREAK", 62);
      Main.Achievements.RegisterIconIndex("THROWING_LINES", 63);
      Main.Achievements.RegisterIconIndex("DYE_HARD", 64);
      Main.Achievements.RegisterIconIndex("FREQUENT_FLYER", 65);
      Main.Achievements.RegisterIconIndex("THE_CAVALRY", 66);
      Main.Achievements.RegisterIconIndex("COMPLETELY_AWESOME", 67);
      Main.Achievements.RegisterIconIndex("TIL_DEATH", 68);
      Main.Achievements.RegisterIconIndex("ARCHAEOLOGIST", 69);
      Main.Achievements.RegisterIconIndex("PRETTY_IN_PINK", 70);
      Main.Achievements.RegisterIconIndex("RAINBOWS_AND_UNICORNS", 71);
      Main.Achievements.RegisterIconIndex("YOU_AND_WHAT_ARMY", 72);
      Main.Achievements.RegisterIconIndex("PRISMANCER", 73);
      Main.Achievements.RegisterIconIndex("IT_CAN_TALK", 74);
      Main.Achievements.RegisterIconIndex("WATCH_YOUR_STEP", 75);
      Main.Achievements.RegisterIconIndex("MARATHON_MEDALIST", 76);
      Main.Achievements.RegisterIconIndex("GLORIOUS_GOLDEN_POLE", 77);
      Main.Achievements.RegisterIconIndex("SERVANT_IN_TRAINING", 78);
      Main.Achievements.RegisterIconIndex("GOOD_LITTLE_SLAVE", 79);
      Main.Achievements.RegisterIconIndex("TROUT_MONKEY", 80);
      Main.Achievements.RegisterIconIndex("FAST_AND_FISHIOUS", 81);
      Main.Achievements.RegisterIconIndex("SUPREME_HELPER_MINION", 82);
      Main.Achievements.RegisterIconIndex("TOPPED_OFF", 83);
      Main.Achievements.RegisterIconIndex("SLAYER_OF_WORLDS", 84);
      Main.Achievements.RegisterIconIndex("YOU_CAN_DO_IT", 85);
      Main.Achievements.RegisterIconIndex("SICK_THROW", 86);
      Main.Achievements.RegisterIconIndex("MATCHING_ATTIRE", 87);
      Main.Achievements.RegisterAchievementCategory("EYE_ON_YOU", AchievementCategory.Slayer);
      Main.Achievements.RegisterAchievementCategory("SLIPPERY_SHINOBI", AchievementCategory.Slayer);
      Main.Achievements.RegisterAchievementCategory("WORM_FODDER", AchievementCategory.Slayer);
      Main.Achievements.RegisterAchievementCategory("MASTERMIND", AchievementCategory.Slayer);
      Main.Achievements.RegisterAchievementCategory("STING_OPERATION", AchievementCategory.Slayer);
      Main.Achievements.RegisterAchievementCategory("BONED", AchievementCategory.Slayer);
      Main.Achievements.RegisterAchievementCategory("STILL_HUNGRY", AchievementCategory.Slayer);
      Main.Achievements.RegisterAchievementCategory("BUCKETS_OF_BOLTS", AchievementCategory.Slayer);
      Main.Achievements.RegisterAchievementCategory("THE_GREAT_SOUTHERN_PLANTKILL", AchievementCategory.Slayer);
      Main.Achievements.RegisterAchievementCategory("LIHZAHRDIAN_IDOL", AchievementCategory.Slayer);
      Main.Achievements.RegisterAchievementCategory("FISH_OUT_OF_WATER", AchievementCategory.Slayer);
      Main.Achievements.RegisterAchievementCategory("OBSESSIVE_DEVOTION", AchievementCategory.Slayer);
      Main.Achievements.RegisterAchievementCategory("STAR_DESTROYER", AchievementCategory.Slayer);
      Main.Achievements.RegisterAchievementCategory("CHAMPION_OF_TERRARIA", AchievementCategory.Slayer);
      Main.Achievements.RegisterAchievementCategory("GOBLIN_PUNTER", AchievementCategory.Slayer);
      Main.Achievements.RegisterAchievementCategory("DO_YOU_WANT_TO_SLAY_A_SNOWMAN", AchievementCategory.Slayer);
      Main.Achievements.RegisterAchievementCategory("WALK_THE_PLANK", AchievementCategory.Slayer);
      Main.Achievements.RegisterAchievementCategory("BALEFUL_HARVEST", AchievementCategory.Slayer);
      Main.Achievements.RegisterAchievementCategory("ICE_SCREAM", AchievementCategory.Slayer);
      Main.Achievements.RegisterAchievementCategory("TIN_FOIL_HATTER", AchievementCategory.Slayer);
      Main.Achievements.RegisterAchievementCategory("TIL_DEATH", AchievementCategory.Slayer);
      Main.Achievements.RegisterAchievementCategory("THERE_ARE_SOME_WHO_CALL_HIM", AchievementCategory.Slayer);
      Main.Achievements.RegisterAchievementCategory("ARCHAEOLOGIST", AchievementCategory.Slayer);
      Main.Achievements.RegisterAchievementCategory("PRETTY_IN_PINK", AchievementCategory.Slayer);
      Main.Achievements.RegisterAchievementCategory("DECEIVER_OF_FOOLS", AchievementCategory.Slayer);
      Main.Achievements.RegisterAchievementCategory("VEHICULAR_MANSLAUGHTER", AchievementCategory.Slayer);
      Main.Achievements.RegisterAchievementCategory("SMASHING_POPPET", AchievementCategory.Explorer);
      Main.Achievements.RegisterAchievementCategory("BEGONE_EVIL", AchievementCategory.Explorer);
      Main.Achievements.RegisterAchievementCategory("ITS_HARD", AchievementCategory.Explorer);
      Main.Achievements.RegisterAchievementCategory("FUNKYTOWN", AchievementCategory.Explorer);
      Main.Achievements.RegisterAchievementCategory("WATCH_YOUR_STEP", AchievementCategory.Explorer);
      Main.Achievements.RegisterAchievementCategory("YOU_CAN_DO_IT", AchievementCategory.Explorer);
      Main.Achievements.RegisterAchievementCategory("BLOODBATH", AchievementCategory.Explorer);
      Main.Achievements.RegisterAchievementCategory("KILL_THE_SUN", AchievementCategory.Explorer);
      Main.Achievements.RegisterAchievementCategory("STICKY_SITUATION", AchievementCategory.Explorer);
      Main.Achievements.RegisterAchievementCategory("NO_HOBO", AchievementCategory.Explorer);
      Main.Achievements.RegisterAchievementCategory("IT_CAN_TALK", AchievementCategory.Explorer);
      Main.Achievements.RegisterAchievementCategory("HEART_BREAKER", AchievementCategory.Explorer);
      Main.Achievements.RegisterAchievementCategory("I_AM_LOOT", AchievementCategory.Explorer);
      Main.Achievements.RegisterAchievementCategory("ROBBING_THE_GRAVE", AchievementCategory.Explorer);
      Main.Achievements.RegisterAchievementCategory("GET_A_LIFE", AchievementCategory.Explorer);
      Main.Achievements.RegisterAchievementCategory("JEEPERS_CREEPERS", AchievementCategory.Explorer);
      Main.Achievements.RegisterAchievementCategory("WHERES_MY_HONEY", AchievementCategory.Explorer);
      Main.Achievements.RegisterAchievementCategory("DUNGEON_HEIST", AchievementCategory.Explorer);
      Main.Achievements.RegisterAchievementCategory("BIG_BOOTY", AchievementCategory.Explorer);
      Main.Achievements.RegisterAchievementCategory("ITS_GETTING_HOT_IN_HERE", AchievementCategory.Explorer);
      Main.Achievements.RegisterAchievementCategory("INTO_ORBIT", AchievementCategory.Explorer);
      Main.Achievements.RegisterAchievementCategory("ROCK_BOTTOM", AchievementCategory.Explorer);
      Main.Achievements.RegisterAchievementCategory("OOO_SHINY", AchievementCategory.Explorer);
      Main.Achievements.RegisterAchievementCategory("EXTRA_SHINY", AchievementCategory.Explorer);
      Main.Achievements.RegisterAchievementCategory("PHOTOSYNTHESIS", AchievementCategory.Explorer);
      Main.Achievements.RegisterAchievementCategory("GELATIN_WORLD_TOUR", AchievementCategory.Challenger);
      Main.Achievements.RegisterAchievementCategory("SLAYER_OF_WORLDS", AchievementCategory.Challenger);
      Main.Achievements.RegisterAchievementCategory("REAL_ESTATE_AGENT", AchievementCategory.Challenger);
      Main.Achievements.RegisterAchievementCategory("YOU_AND_WHAT_ARMY", AchievementCategory.Challenger);
      Main.Achievements.RegisterAchievementCategory("TOPPED_OFF", AchievementCategory.Challenger);
      Main.Achievements.RegisterAchievementCategory("MECHA_MAYHEM", AchievementCategory.Challenger);
      Main.Achievements.RegisterAchievementCategory("BULLDOZER", AchievementCategory.Challenger);
      Main.Achievements.RegisterAchievementCategory("NOT_THE_BEES", AchievementCategory.Challenger);
      Main.Achievements.RegisterAchievementCategory("RAINBOWS_AND_UNICORNS", AchievementCategory.Challenger);
      Main.Achievements.RegisterAchievementCategory("THROWING_LINES", AchievementCategory.Challenger);
      Main.Achievements.RegisterAchievementCategory("FREQUENT_FLYER", AchievementCategory.Challenger);
      Main.Achievements.RegisterAchievementCategory("LUCKY_BREAK", AchievementCategory.Challenger);
      Main.Achievements.RegisterAchievementCategory("MARATHON_MEDALIST", AchievementCategory.Challenger);
      Main.Achievements.RegisterAchievementCategory("SERVANT_IN_TRAINING", AchievementCategory.Challenger);
      Main.Achievements.RegisterAchievementCategory("GOOD_LITTLE_SLAVE", AchievementCategory.Challenger);
      Main.Achievements.RegisterAchievementCategory("TROUT_MONKEY", AchievementCategory.Challenger);
      Main.Achievements.RegisterAchievementCategory("FAST_AND_FISHIOUS", AchievementCategory.Challenger);
      Main.Achievements.RegisterAchievementCategory("SUPREME_HELPER_MINION", AchievementCategory.Challenger);
      Main.Achievements.RegisterAchievementCategory("OBTAIN_HAMMER", AchievementCategory.Collector);
      Main.Achievements.RegisterAchievementCategory("HEAVY_METAL", AchievementCategory.Collector);
      Main.Achievements.RegisterAchievementCategory("STAR_POWER", AchievementCategory.Collector);
      Main.Achievements.RegisterAchievementCategory("MINER_FOR_FIRE", AchievementCategory.Collector);
      Main.Achievements.RegisterAchievementCategory("HEAD_IN_THE_CLOUDS", AchievementCategory.Collector);
      Main.Achievements.RegisterAchievementCategory("DRAX_ATTAX", AchievementCategory.Collector);
      Main.Achievements.RegisterAchievementCategory("PRISMANCER", AchievementCategory.Collector);
      Main.Achievements.RegisterAchievementCategory("SWORD_OF_THE_HERO", AchievementCategory.Collector);
      Main.Achievements.RegisterAchievementCategory("HOLD_ON_TIGHT", AchievementCategory.Collector);
      Main.Achievements.RegisterAchievementCategory("THE_CAVALRY", AchievementCategory.Collector);
      Main.Achievements.RegisterAchievementCategory("DYE_HARD", AchievementCategory.Collector);
      Main.Achievements.RegisterAchievementCategory("MATCHING_ATTIRE", AchievementCategory.Collector);
      Main.Achievements.RegisterAchievementCategory("FASHION_STATEMENT", AchievementCategory.Collector);
      Main.Achievements.RegisterAchievementCategory("COMPLETELY_AWESOME", AchievementCategory.Collector);
      Main.Achievements.RegisterAchievementCategory("TIMBER", AchievementCategory.Collector);
      Main.Achievements.RegisterAchievementCategory("SICK_THROW", AchievementCategory.Collector);
      Main.Achievements.RegisterAchievementCategory("GLORIOUS_GOLDEN_POLE", AchievementCategory.Collector);
      Main.Achievements.RegisterAchievementCategory("TEMPLE_RAIDER", AchievementCategory.Collector);
      Main.Achievements.RegisterAchievementCategory("LIKE_A_BOSS", AchievementCategory.Collector);
      Main.Achievements.Load();
      Main.Achievements.OnAchievementCompleted += new Achievement.AchievementCompleted(AchievementInitializer.OnAchievementCompleted);
      AchievementsHelper.Initialize();
    }

    private static void OnAchievementCompleted(Achievement achievement)
    {
      Main.NewText(Language.GetTextValue("Achievements.Completed", (object) AchievementTagHandler.GenerateTag(achievement)), byte.MaxValue, byte.MaxValue, byte.MaxValue, false);
    }
  }
}
